export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_PRODUCT_PURCHASE = 'ADD_PRODUCT_PURCHASE';
export const PRODUCT_START = 'PRODUCT_START';
